export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const PROCESSING_SETUP = "PROCESSING_SETUP";
export const PROCESSING_SETUP_SUCCESS = "PROCESSING_SETUP_SUCCESS";
export const PROCESSING_SETUP_FAIL = "PROCESSING_SETUP_FAIL";
export const PROCESSING_SETUP_RESET = "PROCESSING_SETUP_RESET";

export const LOAD_PROCESSING_REQUEST = "LOAD_PROCESSING_REQUEST";
export const LOAD_PROCESSING_SUCCESS = "LOAD_PROCESSING_SUCCESS";
export const LOAD_PROCESSING_FAIL = "LOAD_PROCESSING_FAIL";


export const COLLECTIONS_SETUP = "COLLECTIONS_SETUP";
export const COLLECTIONS_SETUP_SUCCESS = "COLLECTIONS_SETUP_SUCCESS";
export const COLLECTIONS_SETUP_FAIL = "COLLECTIONS_SETUP_FAIL";
export const COLLECTIONS_SETUP_RESET = "COLLECTIONS_SETUP_RESET";

export const LOAD_COLLECTIONS_REQUEST = "LOAD_COLLECTIONS_REQUEST";
export const LOAD_COLLECTIONS_SUCCESS = "LOAD_COLLECTIONS_SUCCESS";
export const LOAD_COLLECTIONS_FAIL = "LOAD_COLLECTIONS_FAIL";

export const FINANCE_SETUP = "FINANCE_SETUP";
export const FINANCE_SETUP_SUCCESS = "FINANCE_SETUP_SUCCESS";
export const FINANCE_SETUP_FAIL = "FINANCE_SETUP_FAIL";
export const FINANCE_SETUP_RESET = "FINANCE_SETUP_RESET";

export const LOAD_FINANCE_REQUEST = "LOAD_FINANCE_REQUEST";
export const LOAD_FINANCE_SUCCESS = "LOAD_FINANCE_SUCCESS";
export const LOAD_FINANCE_FAIL = "LOAD_FINANCE_FAIL";

export const INFRASTRUCTURE_SETUP = "INFRASTRUCTURE_SETUP";
export const INFRASTRUCTURE_SETUP_SUCCESS = "INFRASTRUCTURE_SETUP_SUCCESS";
export const INFRASTRUCTURE_SETUP_FAIL = "INFRASTRUCTURE_SETUP_FAIL";
export const INFRASTRUCTURE_SETUP_RESET = "INFRASTRUCTURE_SETUP_RESET";

export const LOAD_INFRASTRUCTURE_REQUEST = "LOAD_INFRASTRUCTURE_REQUEST";
export const LOAD_INFRASTRUCTURE_SUCCESS = "LOAD_INFRASTRUCTURE_SUCCESS";
export const LOAD_INFRASTRUCTURE_FAIL = "LOAD_INFRASTRUCTURE_FAIL";


export const HUMAN_RESOURCES_SETUP = "HUMAN_RESOURCES_SETUP";
export const HUMAN_RESOURCES_SETUP_SUCCESS = "HUMAN_RESOURCES_SETUP_SUCCESS";
export const HUMAN_RESOURCES_SETUP_FAIL = "HUMAN_RESOURCES_SETUP_FAIL";
export const HUMAN_RESOURCES_SETUP_RESET = "HUMAN_RESOURCES_SETUP_RESET";

export const LOAD_HUMAN_RESOURCES_REQUEST = "LOAD_HUMAN_RESOURCES_REQUEST";
export const LOAD_HUMAN_RESOURCES_SUCCESS = "LOAD_HUMAN_RESOURCES_SUCCESS";
export const LOAD_HUMAN_RESOURCES_FAIL = "LOAD_HUMAN_RESOURCES_FAIL";




export const  CURRENT_DATE_SETUP = "CURRENT_DATE_SETUP";